# Site settings
title: Franck Lab
email: jmfranck [at] syr.edu
description: > # this means to ignore newlines until "baseurl:"
    Â©2017 J.M. Franck
baseurl: "/francklab_web/" # the subpath of your site, e.g. /blog/
url: "http://jmfranck.github.io/francklab_web" # the base hostname & protocol for your site
#url: "http://symposium2015.acert.cornell.edu" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  jmfranck
# Build settings
markdown: kramdown
#markdown: redcarpet
VMs_available: True
